### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by joshyZhou** [cschenxiang/DRSformer#1]
Hi，
thanks for sharing your great work! I'm kind of confused about your note 'Here, these datasets we provided are fully paired images, especially SPA-Data.'. Since we download the prepared dataset of SPA-Data and found out it owns the same data as https://github.com/stevewongv/SPANet. We wonder if there is still a dataset consist training samples at 512 x 512 ?

**Comment by cschenxiang** [comment]
We provided dataset of SPA-Data and (https://github.com/stevewongv/SPANet) are same size data,  but the file location is reorganized. One rainy image corresponds to one no-rain image. No need to use txt file to locate the file path.

**Comment by joshyZhou** [comment]
Thanks for your reply. It's clear to me now.
