### ISSUE TITLE
A Question about MEFC(Mixture of experts feature compensat)

### ISSUE THREAD

**Issue by roger308** [cschenxiang/DRSformer#10]
Hello, thanks for the great work.when i tried to use the MEFC block.I find some different with your code and paper.
![image](https://github.com/cschenxiang/DRSformer/assets/120006443/6d42eb2c-e67a-4af3-98cd-3f03019199a9)
It seem that in the final step(skip-connection) ,you use the relu activative function.
But in the paper released without using relu in the final
![image](https://github.com/cschenxiang/DRSformer/assets/120006443/45811566-2d43-4114-899a-b6c8360ecde5)

thanks

**Comment by cschenxiang** [comment]
> Hello, thanks for the great work.when i tried to use the MEFC block.I find some different with your code and paper. ![image](https://user-images.githubusercontent.com/120006443/279107765-6d42eb2c-e67a-4af3-98cd-3f03019199a9.png) It seem that in the final step(skip-connection) ,you use the relu activative function. But in the paper released without using relu in the final ![image](https://user-images.githubusercontent.com/120006443/279108692-45811566-2d43-4114-899a-b6c8360ecde5.png)
> 
> thanks

Thank you for pointing out this detail issue. We apologize for the negligence in expressing the formula (9).

**Comment by roger308** [comment]
Hi,thanks for your certification
