### ISSUE TITLE
How to resume a interrupted training in a terminal of ubuntu

### ISSUE THREAD

**Issue by yingxuanhi** [cschenxiang/DRSformer#11]
Hello! What a awesome work you make!

Excuse me, I accidentally interrupted my training state of DRSformer in a terminal on unbuntu by Ctrl+C. I want to know that how to 

resume the training on the terminal. I have the lastest pth file, such as 

DRSformer/experiments/Deraining_DRSformer/models/net_g_110000.pth'. 

Please give me help. Sorry to disturb you.

**Comment by cschenxiang** [comment]
> Hello! What a awesome work you make!
> 
> Excuse me, I accidentally interrupted my training state of DRSformer in a terminal on unbuntu by Ctrl+C. I want to know that how to
> 
> resume the training on the terminal. I have the lastest pth file, such as
> 
> DRSformer/experiments/Deraining_DRSformer/models/net_g_110000.pth'.
> 
> Please give me help. Sorry to disturb you.

Greetings, in accordance with the scenario you have delineated, should the files DRSformer/experiments/Deraining_DRSformer/training_states/110000.state and DRSformer/experiments/Deraining_DRSformer/models/net_g_110000.pth be present, the execution of the command 'bash train.sh' will resume the training process within the terminal interface.
