### ISSUE TITLE
How to use the Matlab code to generate psnr, sim

### ISSUE THREAD

**Issue by yingxuanhi** [cschenxiang/DRSformer#12]
Hello! Execute me, I have finished the training with Rain200H. 
I want to see the PSNR and SSIM of training. But I don't know your description in the readme (For Rain200L/H and SPA-Data datasets: PSNR and SSIM results are computed by using this Matlab Code).  
I have generated my visual result of draining after finishing training and get nice draining result.

Please tell me how to generate PSNR/SSIM with the Matlab code in detail.

I am sorry to disturb you.

**Comment by cschenxiang** [comment]
> Hello! Execute me, I have finished the training with Rain200H. I want to see the PSNR and SSIM of training. But I don't know your description in the readme (For Rain200L/H and SPA-Data datasets: PSNR and SSIM results are computed by using this Matlab Code). I have generated my visual result of draining after finishing training and get nice draining result.
> 
> Please tell me how to generate PSNR/SSIM with the Matlab code in detail.
> 
> I am sorry to disturb you.

You can download the following resources for testing.
https://github.com/cschenxiang/DRSformer/tree/main/evaluations/Evalution_Rain200L_Rain200H_SPA-Data
