### ISSUE TITLE
dwconv的实际运行效率如何？

### ISSUE THREAD

**Issue by tanbuzheng** [cschenxiang/DRSformer#13]
您好！我看到您模型的FFN中使用到了dwconv，我想知道在实际训练模型的过程中，dwconv的使用会降低训练速度么？是否有方法可以实现dwconv的实际加速？

**Comment by cschenxiang** [comment]
> 您好！我看到您模型的FFN中使用到了dwconv，我想知道在实际训练模型的过程中，dwconv的使用会降低训练速度么？是否有方法可以实现dwconv的实际加速？

您好，关于这个问题我推荐我们团队另一位小伙伴的工作，对您提及的模型加速可能会有所启发，感谢您的关注。https://openaccess.thecvf.com/content/CVPR2023/papers/Kong_Efficient_Frequency_Domain-Based_Transformers_for_High-Quality_Image_Deblurring_CVPR_2023_paper.pdf
