### ISSUE TITLE
Bad resutls on Rain100L

### ISSUE THREAD

**Issue by mikasaq** [cschenxiang/DRSformer#15]
Hi, I'm retraining DRSformer on rain100L using Deraining.yml and DRSformer_200L+SPA_arch.py. But the avarage psnr and ssim on y channel are only 40.05 and 0.986, respectively. Is there something I did not notice? The loss and psnr during training are shown below.
![image](https://github.com/cschenxiang/DRSformer/assets/152263060/8a5a5bd4-53f8-483a-8f21-30a3a18f1ca1)

**Comment by cschenxiang** [comment]
> Hi, I'm retraining DRSformer on rain100L using Deraining.yml and DRSformer_200L+SPA_arch.py. But the avarage psnr and ssim on y channel are only 40.05 and 0.986, respectively. Is there something I did not notice? The loss and psnr during training are shown below. ![image](https://private-user-images.githubusercontent.com/152263060/286189913-8a5a5bd4-53f8-483a-8f21-30a3a18f1ca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTE5OTMsIm5iZiI6MTcwMTE5MTY5MywicGF0aCI6Ii8xNTIyNjMwNjAvMjg2MTg5OTEzLThhNWE1YmQ0LTUzZjgtNDgzYS04ZjIxLTMwYTNhMThmMWNhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQxNzE0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTI3NDg3MjVmNTZmZTUwNjViZDBiMmMxYjNlYTI1ZDQ0ZGE2OTUxOWY4YzBhMzk5ZTljMjc1YjkwNmRmMzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UnEOXXIrj2ZUlI_9Nvtxu63yIM_iwBKT0m_AGEXaOdw)

Our experiment was conducted on the Rain200L dataset. Check the settings for multi GPU training and batch size, and ensure that the code for calculating PSNR is consistent.

**Comment by mikasaq** [comment]
Thank you for your reminder.
