### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by EvaHZY** [cschenxiang/DRSformer#16]
excuse me, what is Baidu net disk data extraction code for DRStransformer？

**Comment by cschenxiang** [comment]
> excuse me, what is Baidu net disk data extraction code for DRStransformer？

Thank you for discovering the issue. It seems that there is a bug on Baidu Cloud currently. I have updated the extracted password.

**Comment by EvaHZY** [comment]
Thanks for help！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月12日(星期二) 下午3:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cschenxiang/DRSformer] data download (Issue #16)





  
excuse me, what is Baidu net disk data extraction code for DRStransformer？
  
Thank you for discovering the issue. It seems that there is a bug on Baidu Cloud currently. I have updated the extracted password.
