### ISSUE TITLE
Adjust the number of iterations for training the model.

### ISSUE THREAD

**Issue by yingxuanhi** [cschenxiang/DRSformer#17]
Hello! I've been experimenting with modifying your work recently. I would like to set the number of iterations for training to 400,000. Additionally, I want to set the learning rate to 2.5e-4 for the first 100,000 iterations and gradually decrease it to 1e-6 for the remaining 300,000 iterations. How can I modify the option file for this?

I'm sorry to disturb your time, Thank you!!

**Comment by cschenxiang** [comment]
> Hello! I've been experimenting with modifying your work recently. I would like to set the number of iterations for training to 400,000. Additionally, I want to set the learning rate to 2.5e-4 for the first 100,000 iterations and gradually decrease it to 1e-6 for the remaining 300,000 iterations. How can I modify the option file for this?
> 
> I'm sorry to disturb your time, Thank you!!


total_iter: 400000
periods: [100000, 400000] 
lr: !!float 2.5e-4
weight_decay: !!float 1e-6

**Comment by yingxuanhi** [comment]
> > Hello! I've been experimenting with modifying your work recently. I would like to set the number of iterations for training to 400,000. Additionally, I want to set the learning rate to 2.5e-4 for the first 100,000 iterations and gradually decrease it to 1e-6 for the remaining 300,000 iterations. How can I modify the option file for this?
> > I'm sorry to disturb your time, Thank you!!
> 
> total_iter: 400000 periods: [100000, 400000] lr: !!float 2.5e-4 weight_decay: !!float 1e-6

**Comment by yingxuanhi** [comment]
>



> > Hello! I've been experimenting with modifying your work recently. I would like to set the number of iterations for training to 400,000. Additionally, I want to set the learning rate to 2.5e-4 for the first 100,000 iterations and gradually decrease it to 1e-6 for the remaining 300,000 iterations. How can I modify the option file for this?
> > I'm sorry to disturb your time, Thank you!!
> 
> total_iter: 400000 periods: [100000, 400000] lr: !!float 2.5e-4 weight_decay: !!float 1e-6



Hello! Thank you sincerely for your response. I have the following questions to ask:

1. In addition to changing total_iter: 300000 to total_iter: 400000 when modifying the total number of iterations,

### ------- Training on single fixed-patch size 128x128 ---------
mini_batch_sizes: [4]
iters: [300000]
gt_size: 128
gt_sizes: [128]
### ------------------------------------------------------------

Is there a need to change iters: [300000] to iters: [400000]? If changed to iters: [400000], is it acceptable?

2. Shouldn't periods: [100000, 400000] be modified to periods: [100000, 300000]?

3. Is there a need to change eta_mins: [0.0003, 0.000001] to eta_mins: [0.00025, 0.000001]? If changed to eta_mins: [0.00025, 0.000001], is it acceptable?

4. What is the purpose of changing weight_decay: !!float 1e-4 to weight_decay: !!float 1e-6?

Thank you very much for your assistance!
