### ISSUE TITLE
About Dataset rain200H, rain200L

### ISSUE THREAD

**Issue by dlwns97** [cschenxiang/DRSformer#25]
Hi! I'm a graduate student researching rain removal, and I'm really interested in the papers you've written. I would love to reproduce your work. 

I've been looking at your previous deraining papers, but I'm unable to access the Rain200H and Rain200L datasets because I can't use Baidu in my region. 

Would it be possible for you to share those datasets with me, please?

**Comment by cschenxiang** [comment]
> Hi! I'm a graduate student researching rain removal, and I'm really interested in the papers you've written. I would love to reproduce your work.
> 
> I've been looking at your previous deraining papers, but I'm unable to access the Rain200H and Rain200L datasets because I can't use Baidu in my region.
> 
> Would it be possible for you to share those datasets with me, please?

Please send your email address.

**Comment by dlwns97** [comment]
> > Hi! I'm a graduate student researching rain removal, and I'm really interested in the papers you've written. I would love to reproduce your work.
> > I've been looking at your previous deraining papers, but I'm unable to access the Rain200H and Rain200L datasets because I can't use Baidu in my region.
> > Would it be possible for you to share those datasets with me, please?
> 
> Please send your email address.

Hi, here is my email address : "dlwns230213@gmail.com". 
Thanks for your help.
