### ISSUE TITLE
PNG images in the test dataset of DDN

### ISSUE THREAD

**Issue by 619lyj** [cschenxiang/DRSformer#5]
The GT picture in the test picture of DDN's matlab is in PNg format. Could you please provide this picture in png format in the form of Baidu Wangpan.
Because when I used JPG format images for verification, the accuracy was slightly lower than the results in the paper.

**Comment by cschenxiang** [comment]
> The GT picture in the test picture of DDN's matlab is in PNg format. Could you please provide this picture in png format in the form of Baidu Wangpan. Because when I used JPG format images for verification, the accuracy was slightly lower than the results in the paper.

https://pan.baidu.com/s/1vR3ioLJSbcgxEv0Dfoc0hQ?pwd=wif8
