### ISSUE TITLE
Question about datasets

### ISSUE THREAD

**Issue by DivineKim** [cschenxiang/DRSformer#7]
Hello, thanks for the great work, I've been trying to download the datasets but all the files turn out to be empty after the download. Is there a way I could get the datasets again? Thanks in advance

**Comment by cschenxiang** [comment]
> Hello, thanks for the great work, I've been trying to download the datasets but all the files turn out to be empty after the download. Is there a way I could get the datasets again? Thanks in advance

Thanks for your attention. I rechecked the dataset download link and did not find the issue you mentioned.

**Comment by DivineKim** [comment]
![Screenshot from 2023-08-30 21-46-29](https://github.com/cschenxiang/DRSformer/assets/92572236/7147fe3d-b12c-4405-bebf-79dae1555360)
![Screenshot from 2023-08-30 21-47-27](https://github.com/cschenxiang/DRSformer/assets/92572236/42234ba6-0153-4ee1-bc92-c738f6621853)
