### ISSUE TITLE
Additional requirements for baseline model weight files trained on SPA-Data, Thank you !

### ISSUE THREAD

**Issue by GN222A222** [cschenxiang/DRSformer#8]
Hello, your work is great and solid, and you have also open sourced the visual data of many baseline models. 
I have an additional request. You have shared the weight file of DRSformer training on SPAData. Can you share the model weight files (such as .pth) of other baselines trained on SPA-Data? 
I would like to conduct additional experiments on some real data.
If possible, thank you very much!!
![baselines](https://github.com/cschenxiang/DRSformer/assets/90634826/d5c97cf1-6e81-40b8-ab0f-5b819f422741)

**Comment by cschenxiang** [comment]
> Hello, your work is great and solid, and you have also open sourced the visual data of many baseline models. I have an additional request. You have shared the weight file of DRSformer training on SPAData. Can you share the model weight files (such as .pth) of other baselines trained on SPA-Data? I would like to conduct additional experiments on some real data. If possible, thank you very much!! ![baselines](https://user-images.githubusercontent.com/90634826/274509042-d5c97cf1-6e81-40b8-ab0f-5b819f422741.png)

Thanks for your attention to our work. You can find the training weights of SPAData through the following link.

DualGCN：https://xueyangfu.github.io/paper/2021/AAAI/code.zip
SPDNet: https://github.com/Joyies/SPDNet
IDT：https://github.com/jiexiaou/IDT
