### ISSUE TITLE
Question about attention compute

### ISSUE THREAD

**Issue by 591582523h** [cschenxiang/DRSformer#9]
在[DRSformer_arch.py](https://github.com/cschenxiang/DRSformer/blob/main/basicsr/models/archs/DRSformer_arch.py)的第124到138行，您计算时使用的是C x HW 的 query 和 HW x C 的 value，这和普通的Attention计算相反，这有什么特殊的设计吗？

**Comment by cschenxiang** [comment]
> 在[DRSformer_arch.py](https://github.com/cschenxiang/DRSformer/blob/main/basicsr/models/archs/DRSformer_arch.py)的第124到138行，您计算时使用的是C x HW 的 query 和 HW x C 的 value，这和普通的Attention计算相反，这有什么特殊的设计吗？

您好，这个设计我们与https://github.com/swz30/Restormer中保持一致，目的是减小计算复杂度，具体可参考Restormer原文。
